ingress:
    enabled: true
    rules:
        -   host: kor.localtest.me
            http:
                paths:
                    -   backend:
                            service:
                                name: liferay-default
                                port:
                                    name: http
                        path: /
                        pathType: ImplementationSpecific