customVolumeMounts:
    x-mountlocal:
        -   mountPath: /mnt/local
            name: mount-local
customVolumes:
    x-mountlocal:
        -   hostPath:
                path: /mnt/local
            name: mount-local