#
# Application
#

liferay.customer.gcf.base.url=${LIFERAY_CUSTOMER_GCF_BASE_URL}
liferay.customer.gcf.service.account.key=${LIFERAY_CUSTOMER_GCF_SERVICE_ACCOUNT_KEY}
liferay.customer.gcs.bucket.name=${LIFERAY_CUSTOMER_GCS_BUCKET_NAME}
liferay.customer.gcs.service.account.key=${LIFERAY_CUSTOMER_GCS_SERVICE_ACCOUNT_KEY}
liferay.customer.jira.api.email.address=${LIFERAY_CUSTOMER_JIRA_API_EMAIL_ADDRESS}
liferay.customer.jira.api.token=${LIFERAY_CUSTOMER_JIRA_API_TOKEN}
liferay.customer.jira.url=${LIFERAY_CUSTOMER_JIRA_URL}
liferay.osb.spring.boot.client.zendesk.api.email.address=${LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_API_EMAIL_ADDRESS}
liferay.osb.spring.boot.client.zendesk.api.token=${LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_API_TOKEN}
liferay.osb.spring.boot.client.zendesk.url=${LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_URL}

#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
    liferay-customer-etc-spring-boot-oahs,\
    liferay-customer-etc-spring-boot-oaua

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081