liferay_customer_gcs_bucket_name=${LIFERAY_CUSTOMER_GCS_BUCKET_NAME}
liferay_customer_gcs_service_account_key=${LIFERAY_CUSTOMER_GCS_SERVICE_ACCOUNT_KEY}
liferay_osb_spring_boot_client_zendesk_api_email_address=${LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_API_EMAIL_ADDRESS}
liferay_osb_spring_boot_client_zendesk_api_token=${LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_API_TOKEN}
liferay_osb_spring_boot_client_zendesk_url=${LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_URL}

server.port=${SERVER_PORT}

spring.config.import=\
    classpath:/application-default.properties,\
    optional:configtree:${LIFERAY_ROUTES_CLIENT_EXTENSION}/,\
    optional:configtree:${LIFERAY_ROUTES_DXP}/