#
# Application
#

liferay.one.analytics.cloud.auth.email.address=${LIFERAY_ONE_ANALYTICS_CLOUD_AUTH_EMAIL_ADDRESS}
liferay.one.analytics.cloud.auth.password=${LIFERAY_ONE_ANALYTICS_CLOUD_AUTH_PASSWORD}
liferay.one.analytics.cloud.auth.url=${LIFERAY_ONE_ANALYTICS_CLOUD_AUTH_URL}
liferay.one.analytics.cloud.internal.auth.email.address=${LIFERAY_ONE_ANALYTICS_CLOUD_INTERNAL_AUTH_EMAIL_ADDRESS}
liferay.one.analytics.cloud.internal.auth.password=${LIFERAY_ONE_ANALYTICS_CLOUD_INTERNAL_AUTH_PASSWORD}
liferay.one.analytics.cloud.internal.auth.url=${LIFERAY_ONE_ANALYTICS_CLOUD_INTERNAL_AUTH_URL}
liferay.one.console.auth.email.address=${LIFERAY_ONE_CONSOLE_AUTH_EMAIL_ADDRESS}
liferay.one.console.auth.password=${LIFERAY_ONE_CONSOLE_AUTH_PASSWORD}
liferay.one.console.auth.url=${LIFERAY_ONE_CONSOLE_AUTH_URL}
liferay.one.console.cluster=${LIFERAY_ONE_CONSOLE_CLUSTER}
liferay.one.console.project.prefix=${LIFERAY_ONE_CONSOLE_PROJECT_PREFIX}
liferay.one.console.project.uid=${LIFERAY_ONE_CONSOLE_PROJECT_UID}
liferay.one.console.ssa.cluster=${LIFERAY_ONE_CONSOLE_SSA_CLUSTER}
liferay.one.console.ssa.project.prefix=${LIFERAY_ONE_CONSOLE_SSA_PROJECT_PREFIX}
liferay.one.console.ssa.project.uid=${LIFERAY_ONE_CONSOLE_SSA_PROJECT_UID}
liferay.one.gcs.bucket.name=${LIFERAY_ONE_GCS_BUCKET_NAME}
liferay.one.gcs.service.account.key=${LIFERAY_ONE_GCS_SERVICE_ACCOUNT_KEY}
liferay.one.jira.account.role.sync.cron=0 0 0 * * SUN
liferay.one.jira.api.email.address=${LIFERAY_ONE_JIRA_API_EMAIL_ADDRESS}
liferay.one.jira.api.token=${LIFERAY_ONE_JIRA_API_TOKEN}
liferay.one.jira.asset.schema.name=${LIFERAY_ONE_JIRA_ASSET_SCHEMA_NAME}
liferay.one.jira.issue.provisioning.field.country=${LIFERAY_ONE_JIRA_ISSUE_PROVISIONING_FIELD_COUNTRY}
liferay.one.jira.issue.provisioning.field.offering=${LIFERAY_ONE_JIRA_ISSUE_PROVISIONING_FIELD_OFFERING}
liferay.one.jira.issue.provisioning.field.organization=${LIFERAY_ONE_JIRA_ISSUE_PROVISIONING_FIELD_ORGANIZATION}
liferay.one.jira.issue.provisioning.field.owner=${LIFERAY_ONE_JIRA_ISSUE_PROVISIONING_FIELD_OWNER}
liferay.one.jira.issue.provisioning.field.provisioning.component=${LIFERAY_ONE_JIRA_ISSUE_PROVISIONING_FIELD_PROVISIONING_COMPONENT}
liferay.one.jira.issue.provisioning.field.support.region=${LIFERAY_ONE_JIRA_ISSUE_PROVISIONING_FIELD_SUPPORT_REGION}
liferay.one.jira.issue.provisioning.id=${LIFERAY_ONE_JIRA_ISSUE_PROVISIONING_ID}
liferay.one.jira.issue.provisioning.offering.id=${LIFERAY_ONE_JIRA_ISSUE_PROVISIONING_OFFERING_ID}
liferay.one.jira.issue.support.hc.field.organization=${LIFERAY_ONE_JIRA_ISSUE_SUPPORT_HC_FIELD_ORGANIZATION}
liferay.one.jira.issue.support.hc.field.request.type=${LIFERAY_ONE_JIRA_ISSUE_SUPPORT_HC_FIELD_REQUEST_TYPE}
liferay.one.jira.organization.provisioning.id=${LIFERAY_ONE_JIRA_ORGANIZATION_PROVISIONING_ID}
liferay.one.jira.organization.role.sync.cron=0 0 0 * * SUN
liferay.one.jira.project.support.fls=${LIFERAY_ONE_JIRA_PROJECT_SUPPORT_FLS}
liferay.one.jira.project.support.fls.url=${LIFERAY_ONE_JIRA_PROJECT_SUPPORT_FLS_URL}
liferay.one.jira.project.support.hc=${LIFERAY_ONE_JIRA_PROJECT_SUPPORT_HC}
liferay.one.jira.project.support.hc.url=${LIFERAY_ONE_JIRA_PROJECT_SUPPORT_HC_URL}
liferay.one.jira.request.provisioning.id=${LIFERAY_ONE_JIRA_REQUEST_PROVISIONING_ID}
liferay.one.jira.team.role.sync.cron=0 0 * * * *
liferay.one.jira.url=${LIFERAY_ONE_JIRA_URL}
liferay.one.jira.workspace.id=${LIFERAY_ONE_JIRA_WORKSPACE_ID}
liferay.one.portal.url=${LIFERAY_ONE_PORTAL_URL}
liferay.one.product.version.sync.cron=0 0 0 * * SUN
liferay.one.product.version.sync.product.groups=dxp
liferay.one.product.version.sync.releases.url=https://releases.liferay.com/releases.json
liferay.one.provisioning.email.address.australia=${LIFERAY_ONE_PROVISIONING_EMAIL_ADDRESS_AUSTRALIA}
liferay.one.provisioning.email.address.brazil=${LIFERAY_ONE_PROVISIONING_EMAIL_ADDRESS_BRAZIL}
liferay.one.provisioning.email.address.china=${LIFERAY_ONE_PROVISIONING_EMAIL_ADDRESS_CHINA}
liferay.one.provisioning.email.address.global=${LIFERAY_ONE_PROVISIONING_EMAIL_ADDRESS_GLOBAL}
liferay.one.provisioning.email.address.hungary=${LIFERAY_ONE_PROVISIONING_EMAIL_ADDRESS_HUNGARY}
liferay.one.provisioning.email.address.india=${LIFERAY_ONE_PROVISIONING_EMAIL_ADDRESS_INDIA}
liferay.one.provisioning.email.address.japan=${LIFERAY_ONE_PROVISIONING_EMAIL_ADDRESS_JAPAN}
liferay.one.provisioning.email.address.spain=${LIFERAY_ONE_PROVISIONING_EMAIL_ADDRESS_SPAIN}
liferay.one.provisioning.email.address.us=${LIFERAY_ONE_PROVISIONING_EMAIL_ADDRESS_US}
liferay.one.provisioning.partner.user.update.recipient=${LIFERAY_ONE_PROVISIONING_PARTNER_USER_UPDATE_RECIPIENT}
liferay.one.trial.dxp.domain=${LIFERAY_ONE_TRIAL_DXP_DOMAIN}
liferay.one.trial.max.instances=${LIFERAY_ONE_TRIAL_MAX_INSTANCES:50}
liferay.one.trial.ssa.dxp.domain=${LIFERAY_ONE_TRIAL_SSA_DXP_DOMAIN}
liferay.one.usage.report.cron=${LIFERAY_ONE_USAGE_REPORT_CRON:0 0 2 1 * *}

#
# Email Address Validator
#

liferay.one.email.address.validator.liferay.domains=bp.liferay.com,connect.liferay.com,dev.liferay.com,gs.liferay.com,in.liferay.com,liferay.com,liferay.io,testray.io

#
# OAuth
#

liferay-one-etc-spring-boot-oahs.oauth2.headless.server.client.secret=${LIFERAY_ONE_ETC_SPRING_BOOT_OAHS_CLIENT_SECRET:myfancypassword}

liferay.oauth.application.external.reference.codes=\
    external-ai-hub,\
    external-ssa,\
    external-trial,\
    liferay-one-etc-spring-boot-oahs,\
    liferay-one-etc-spring-boot-oaua

liferay.oauth.urls.excludes=/ready

#
# Okta
#

liferay.one.okta.api.token=${LIFERAY_ONE_OKTA_API_TOKEN}
liferay.one.okta.app.created.pubsub.subscriber.enabled=${LIFERAY_ONE_OKTA_APP_CREATED_PUBSUB_SUBSCRIBER_ENABLED}
liferay.one.okta.app.created.pubsub.subscriber.project.id=${LIFERAY_ONE_OKTA_APP_CREATED_PUBSUB_SUBSCRIBER_PROJECT_ID}
liferay.one.okta.app.created.pubsub.subscriber.subscription=${LIFERAY_ONE_OKTA_APP_CREATED_PUBSUB_SUBSCRIBER_SUBSCRIPTION}
liferay.one.okta.app.created.pubsub.subscriber.topic=${LIFERAY_ONE_OKTA_APP_CREATED_PUBSUB_SUBSCRIBER_TOPIC}
liferay.one.okta.host=${LIFERAY_ONE_OKTA_HOST}
liferay.one.okta.pubsub.publisher.project.id=${LIFERAY_ONE_OKTA_PUBSUB_PUBLISHER_PROJECT_ID}
liferay.one.okta.users.pubsub.subscriber.enabled=${LIFERAY_ONE_OKTA_USERS_PUBSUB_SUBSCRIBER_ENABLED}
liferay.one.okta.users.pubsub.subscriber.project.id=${LIFERAY_ONE_OKTA_USERS_PUBSUB_SUBSCRIBER_PROJECT_ID}
liferay.one.okta.users.pubsub.subscriber.subscription=${LIFERAY_ONE_OKTA_USERS_PUBSUB_SUBSCRIBER_SUBSCRIPTION}
liferay.one.okta.users.pubsub.subscriber.topic=${LIFERAY_ONE_OKTA_USERS_PUBSUB_SUBSCRIBER_TOPIC}

#
# Salesforce
#

liferay.one.salesforce.gcf.audience=${LIFERAY_ONE_SALESFORCE_GCF_AUDIENCE}
liferay.one.salesforce.gcf.base.url=${LIFERAY_ONE_SALESFORCE_GCF_BASE_URL}
liferay.one.salesforce.gcf.service.account.key=${LIFERAY_ONE_SALESFORCE_GCF_SERVICE_ACCOUNT_KEY}
liferay.one.salesforce.object.pubsub.subscriber.enabled=${LIFERAY_ONE_SALESFORCE_OBJECT_PUBSUB_SUBSCRIBER_ENABLED}
liferay.one.salesforce.object.pubsub.subscriber.project.id=${LIFERAY_ONE_SALESFORCE_OBJECT_PUBSUB_SUBSCRIBER_PROJECT_ID}
liferay.one.salesforce.object.pubsub.subscriber.subscription=${LIFERAY_ONE_SALESFORCE_OBJECT_PUBSUB_SUBSCRIBER_SUBSCRIPTION}
liferay.one.salesforce.object.pubsub.subscriber.topic=${LIFERAY_ONE_SALESFORCE_OBJECT_PUBSUB_SUBSCRIBER_TOPIC}
liferay.one.salesforce.opportunity.pubsub.subscriber.enabled=${LIFERAY_ONE_SALESFORCE_OPPORTUNITY_PUBSUB_SUBSCRIBER_ENABLED}
liferay.one.salesforce.opportunity.pubsub.subscriber.project.id=${LIFERAY_ONE_SALESFORCE_OPPORTUNITY_PUBSUB_SUBSCRIBER_PROJECT_ID}
liferay.one.salesforce.opportunity.pubsub.subscriber.subscription=${LIFERAY_ONE_SALESFORCE_OPPORTUNITY_PUBSUB_SUBSCRIBER_SUBSCRIPTION}
liferay.one.salesforce.opportunity.pubsub.subscriber.topic=${LIFERAY_ONE_SALESFORCE_OPPORTUNITY_PUBSUB_SUBSCRIBER_TOPIC}

#
# Spring Boot
#

server.port=58081
spring.messages.basename=content/Language
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
spring.task.scheduling.pool.size=10