#
# Application
#

liferay.one.gcs.bucket.name=${LIFERAY_ONE_GCS_BUCKET_NAME}
liferay.one.gcs.service.account.key=${LIFERAY_ONE_GCS_SERVICE_ACCOUNT_KEY}
liferay.one.jira.api.email.address=${LIFERAY_ONE_JIRA_API_EMAIL_ADDRESS}
liferay.one.jira.api.token=${LIFERAY_ONE_JIRA_API_TOKEN}
liferay.one.jira.organization.asset.object.type.attribute.external.key=${LIFERAY_ONE_JIRA_ORGANIZATION_ASSET_OBJECT_TYPE_ATTRIBUTE_EXTERNAL_KEY}
liferay.one.jira.support.fls.portal.url=${LIFERAY_ONE_JIRA_SUPPORT_FLS_PORTAL_URL}
liferay.one.jira.support.fls.project=${LIFERAY_ONE_JIRA_SUPPORT_FLS_PROJECT}
liferay.one.jira.support.hc.field.organization=${LIFERAY_ONE_JIRA_SUPPORT_HC_FIELD_ORGANIZATION}
liferay.one.jira.support.hc.field.request.type=${LIFERAY_ONE_JIRA_SUPPORT_HC_FIELD_REQUEST_TYPE}
liferay.one.jira.support.hc.portal.url=${LIFERAY_ONE_JIRA_SUPPORT_HC_PORTAL_URL}
liferay.one.jira.support.hc.project=${LIFERAY_ONE_JIRA_SUPPORT_HC_PROJECT}
liferay.one.jira.url=${LIFERAY_ONE_JIRA_URL}
liferay.one.jira.workspace.id=${LIFERAY_ONE_JIRA_WORKSPACE_ID}
liferay.one.portal.url=${LIFERAY_ONE_PORTAL_URL}

#
# Email Address Validator
#

liferay.one.email.address.validator.liferay.domains=bp.liferay.com,connect.liferay.com,dev.liferay.com,gs.liferay.com,in.liferay.com,liferay.com,liferay.io,testray.io

#
# OAuth
#

liferay-one-etc-spring-boot-oahs.oauth2.headless.server.client.secret=${LIFERAY_ONE_ETC_SPRING_BOOT_OAHS_CLIENT_SECRET:myfancypassword}

liferay.oauth.application.external.reference.codes=\
    liferay-one-etc-spring-boot-oahs,\
    liferay-one-etc-spring-boot-oaua

liferay.oauth.urls.excludes=/ready

#
# Okta
#

liferay.one.okta.api.token=${LIFERAY_ONE_OKTA_API_TOKEN}
liferay.one.okta.host=${LIFERAY_ONE_OKTA_HOST}
liferay.one.okta.pubsub.publisher.project.id=${LIFERAY_ONE_OKTA_PUBSUB_PUBLISHER_PROJECT_ID}

#
# Salesforce
#

liferay.one.salesforce.object.pubsub.subscriber.enabled=${LIFERAY_ONE_SALESFORCE_OBJECT_PUBSUB_SUBSCRIBER_ENABLED}
liferay.one.salesforce.object.pubsub.subscriber.project.id=${LIFERAY_ONE_SALESFORCE_OBJECT_PUBSUB_SUBSCRIBER_PROJECT_ID}
liferay.one.salesforce.object.pubsub.subscriber.subscription=${LIFERAY_ONE_SALESFORCE_OBJECT_PUBSUB_SUBSCRIBER_SUBSCRIPTION}
liferay.one.salesforce.object.pubsub.subscriber.topic=${LIFERAY_ONE_SALESFORCE_OBJECT_PUBSUB_SUBSCRIBER_TOPIC}

#
# Spring Boot
#

server.port=58081
spring.messages.basename=content/Language
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false