clientExtensionConfig:
    kind: Deployment
    mainDomain: springboot.localtest.me
    mountInitConfig: true
    setupMainDomainOnCoreDNS: true
    virtualInstanceId: cp.dxp.localtest.me
env:
    COM_LIFERAY_LXC_DXP_DOMAINS: ""
    COM_LIFERAY_LXC_DXP_MAINDOMAIN: ""
    COM_LIFERAY_LXC_DXP_SERVER_PROTOCOL: ""
    LIFERAY_CUSTOMER_GCF_BASE_URL: ""
    LIFERAY_CUSTOMER_GCF_SERVICE_ACCOUNT_KEY: ""
    LIFERAY_CUSTOMER_GCS_BUCKET_NAME: ""
    LIFERAY_CUSTOMER_GCS_SERVICE_ACCOUNT_KEY: ""
    LIFERAY_CUSTOMER_JIRA_API_EMAIL_ADDRESS: ""
    LIFERAY_CUSTOMER_JIRA_API_TOKEN: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_AFFECTED_VERSIONS_DETAILS: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_AFFECTS: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CATEGORIES: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CUSTOMER_PORTAL_DESCRIPTION: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CUSTOMER_PORTAL_SUMMARY: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CUSTOMER_PUBLISHING_DATE: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CVE_IDS: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CVSS_BASE_SCORE: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CVSS_VECTOR_STRING: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_CWE_IDS: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_FIX_VERSIONS: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_ISSUE_CLASSIFICATION: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_PARTNER_PUBLISHING_DATE: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_PUBLISHING_STATUS: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_FIELD_SEVERITY: ""
    LIFERAY_CUSTOMER_JIRA_SECURITY_VULNERABILITY_PROJECT: ""
    LIFERAY_CUSTOMER_JIRA_SERVICE_AFFECTED_VERSIONS_CACHE_EVICTION_CRON: ""
    LIFERAY_CUSTOMER_JIRA_SERVICE_ISSUES_CACHE_EVICTION_CRON: ""
    LIFERAY_CUSTOMER_JIRA_SUPPORT_ENABLED: ""
    LIFERAY_CUSTOMER_JIRA_SUPPORT_FLS_PORTAL_URL: ""
    LIFERAY_CUSTOMER_JIRA_SUPPORT_FLS_PROJECT: ""
    LIFERAY_CUSTOMER_JIRA_SUPPORT_HC_FIELD_BUSINESS_EVENT: ""
    LIFERAY_CUSTOMER_JIRA_SUPPORT_HC_FIELD_ORGANIZATION: ""
    LIFERAY_CUSTOMER_JIRA_SUPPORT_HC_FIELD_REQUEST_TYPE: ""
    LIFERAY_CUSTOMER_JIRA_SUPPORT_HC_PORTAL_URL: ""
    LIFERAY_CUSTOMER_JIRA_SUPPORT_HC_PROJECT: ""
    LIFERAY_CUSTOMER_JIRA_WORKSPACE_ID: ""
    LIFERAY_CUSTOMER_JIRA_URL: ""
    LIFERAY_CUSTOMER_KORONEIKI_AUTH_TOKEN: ""
    LIFERAY_CUSTOMER_KORONEIKI_URL: ""
    LIFERAY_CUSTOMER_OVERDUE_BUSINESS_EVENT_CRON: ""
    LIFERAY_CUSTOMER_PORTAL_URL: ""
    LIFERAY_CUSTOMER_VERSION_LIST_TYPE_API: ""
    LIFERAY_CUSTOMER_VERSION_LIST_TYPE_CRON: ""
    LIFERAY_CUSTOMER_VERSION_LIST_TYPE_DXP_MAJOR_ERC: ""
    LIFERAY_CUSTOMER_VERSION_LIST_TYPE_DXP_MINOR_ERC: ""
    LIFERAY_CUSTOMER_VERSION_LIST_TYPE_DXP_MINOR_PORTAL_MAJOR_ERC: ""
    LIFERAY_CUSTOMER_VERSION_LIST_TYPE_PORTAL_MAJOR_VERSIONS: ""
    LIFERAY_CUSTOMER_VERSION_LIST_TYPE_RELEASES_URL: ""
    LIFERAY_CUSTOMER_ZENDESK_BUSINESS_EVENT_TICKET_FIELD_ID: ""
    LIFERAY_CUSTOMER_ZENDESK_HEAT_TAG_TICKET_FIELD_ID: ""
    LIFERAY_OAUTH_APPLICATION_EXTERNAL_REFERENCE_CODES: ""
    LIFERAY_OAUTH_URLS_EXCLUDES: ""
    LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_API_EMAIL_ADDRESS: ""
    LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_API_TOKEN: ""
    LIFERAY_OSB_SPRING_BOOT_CLIENT_ZENDESK_URL: ""
    SERVER_PORT: ""
    SPRING_BOOT_WEB_CLIENT_MAX_IN_MEMORY_SIZE: ""
image:
    repository: liferay-customer-etc-spring-boot
ingress:
    enabled: true
livenessProbe:
    httpGet:
        path: /ready
readinessProbe:
    httpGet:
        path: /ready
service:
    enabled: true
    port: 58081
